### ISSUE TITLE
Improve your Exception Handling

### ISSUE THREAD

**Issue by fsylkaj** [TGM-HIT/sew9-2324-worttrainer-lsindija#2]
Dear Mr. Sindija, 

While I was looking through your code and trying the nice Worttrainer, I noticed some random chrashes. Please take this aspect into consideration and improve your exception handling! 

I wish you alll the best and success! 

Sincerely, 
Florian Sylkaj

**Comment by lsindija** [comment]
Dear Mr. Sylkaj,

I improved the Exception Handling in the latest commit

Sincerely,
Leon Sindija
